workdir: compare_assembly

# Setting for SV analysis
# gff always relative to the workdir

gffinput: /path/to/gff

# Setting for rna-seq analysis
rna_seq: True
reference: {ref}
# diamond protein db for blast 
refprot: /ref/to/diamondprotdb
rna_basedir: /ref/to/fastq_rna

