workdir: graph_trial

# Setting for SV analysis
# gff always relative to the workdir

gffinput: assembly/Bos_taurus.ARS-UCD1.2.101.gff3.gz

# Setting for rna-seq analysis
rna_seq: False
reference: UCD

# diamond protein db for blast 
refprot: /cluster/work/pausch/danang/pangenome_nonref/result/bsw_ucd_new/annot_analysis/refprot/bos_prot
rna_basedir: /cluster/work/pausch/danang/pangenome_nonref/data/hybrid_assem/bovine_minigraph/nonref_ins/rna_seq/qc_reads

# setting for wgs analysis
dna_seq: True
dna_basedir: /cluster/work/pausch/inputs/fastq/BTA
dna_ref: 
         - UCD
         - graphord
dna_anims:
        - BSWCHEM120060662634
        - BSWCHEM110556008244
        - BSWCHEM110098063770
        - BSWCHEM110471084194
        - BSWCHEM111030024286
        - BSWCHEM120052037815
        - BSWCHEM110203063244
        - BSWCHEM120032300663
        - BSWCHEM110097189518
        - BSWCHEM110269048407
        - BSWCHEM110294048847
        - BSWCHEM110480021128
        - BSWCHEM110106053793
        - BSWCHEM110349149437
        - BSWCHEM120033898589
        - BSWCHEM120060730418
        - BSWCHEM120047653969
        - BSWCHEM111453045080
        - BSWCHEM120070757016
        - BSWCHEM110222168241
        - RM0121
        - RM2148
        - RM2152
        - RM2156
        - RM2158
        - RM2164
        - RM2165
        - RM2169
        - RM2171
        - RM2173
        - RM2792
        - RM2815
        - RM2817
        - RM2821
        - RM2824
        - RM2833
        - RM2852
        - RM2881
        - RM2882
        - RM2884
