workdir: compare_assembly

# Setting for SV analysis
# gff always relative to the workdir

gffinput: assembly/Bos_taurus.ARS-UCD1.2.101.gff3.gz

# Setting for rna-seq analysis

rna_seq: True
rna_basedir: /cluster/work/pausch/danang/pangenome_nonref/data/hybrid_assem/bovine_minigraph/nonref_ins/rna_seq/qc_reads

